name: Icarus Simulation

on: 
  push:
    branches: [master]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag icarus-sim:$(date +%s)
