name: Icarus Simulation

on: 
  push:
    branches: [master]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v1
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag icarus-simulation:$(date +%s)
      - name: Make the script file executable
        run: chmod +x iverilog_run.sh
      - name: Run Icarus
        run: ./iverilog_run.sh
        shell: bash
